{% set name = "fmt" %}
{% set version = "10.2.0" %}
{% set sha256 = "3ca91733a7313a8ad41c0885929415f8ec0a2a31d4dc7e27e9331412f4ca26ac" %}

package:
  name: {{ name|lower }}
  version: 10.1.1

source:
  url: https://github.com/fmtlib/fmt/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('fmt', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/fmt  # [unix]
    - test -f ${PREFIX}/include/fmt/core.h  # [unix]
    - test -f ${PREFIX}/include/fmt/format.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/libfmt.so  # [linux]
    - test -f ${PREFIX}/lib/libfmt.dylib  # [osx]
    - if not exist %LIBRARY_PREFIX%\include\fmt\core.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\fmt\format.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\fmt\fmt-config.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\fmt.dll (exit 1)  # [win]
    # Integration test that we did not break mamba.
    # On a minor or patch version jump, this is going to keep the "local" fmt.
    # On a major version jump this is going to replace the "local" fmt with the
    # previous one (and not test anything until libmmamba has been rebuilt with
    # this fmt.)
    - conda install -y --use-local --no-channel-priority mamba
    # Run a command that loads the shared libmamba and libfmt (and check that
    # all symbols can be resolved.)
    - mamba --version

about:
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
  description: |
    {fmt} is an open-source formatting library for C++.
    It can be used as a safe and fast alternative to (s)printf and iostreams.
  doc_url: https://fmt.dev/latest/
  dev_url: https://github.com/fmtlib/fmt

extra:
  recipe-maintainers:
    - tdegeus
    - vitaut
    - saraedum
    - bdice
